version: "3.9"
networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
services:
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus:v2.47.0
    user: "1002"
    environment:
     - PUID=1002
     - PGID=1002
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/monitoring/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' 
      - '--storage.tsdb.path=/prometheus' 
      - '--web.console.libraries=/etc/prometheus/console_libraries' 
      - '--web.console.templates=/etc/prometheus/consoles' 
      - '--web.enable-lifecycle' 
    ports:
      - 9090:9090
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana:10.1.2-ubuntu
    user: "1002"
    container_name: grafana
    ports:
     - 3000:3000
    restart: unless-stopped
    volumes:
      - /home/monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /home/monitoring/grafana:/var/lib/grafana
    networks:
      - monitoring
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
      - 8081:8080
    networks:
      - monitoring
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro